resolution: workspace
name: services
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.13.5

dependencies:
  shared_preferences: ^2.5.6
  flutter_secure_storage: ^11.2.0
  injectable: ^3.0.0

  alam_el_marateb_constants: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
