name: alam_el_marateb
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
- apps/staff
- apps/customer
- apps/admin
- packages/core/network
- packages/core/storage
- packages/core/utils
- packages/core/auth
- packages/core/notifications
- packages/core/files
- packages/core/design_system
- packages/core/api
- packages/modules/auth
- packages/modules/catalog
- packages/modules/pos
- packages/modules/inventory
- packages/modules/delivery
- packages/modules/orders
- packages/modules/crm

dependency_overrides:
  intl: ^0.20.3
