name: pos
resolution: workspace
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  get_it: ^9.2.1
  api_client:
    path: ../../core/api_client
  core_utils:
    path: ../../core/utils
  core_network:
    path: ../../core/network
  design_system:
    path: ../../core/design_system
dev_dependencies:
  build_runner: ^2.13.1
  freezed: ^4.0.1
  json_serializable: ^6.13.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  flutter_lints: ^6.0.0
