name: design_system
resolution: workspace
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  iconsax_flutter: ^1.0.1
  flutter_svg: ^2.2.4
  cached_network_image_ce: ^4.10.0
  skeletonizer: ^3.0.0
  smooth_page_indicator: ^3.0.0
  carousel_slider: ^5.1.2
  curved_labeled_navigation_bar: ^2.0.6
  country_flags: ^4.1.2
  modal_bottom_sheet: ^3.0.0
  pinput: ^6.0.2
  toastification: ^3.2.0
  flutter_hooks: ^0.21.3+1
  infinite_scroll_pagination: ^5.1.1
  nested: ^1.0.0
dev_dependencies:
  intl_utils: ^2.8.14
  flutter_lints: ^6.0.0
