resolution: workspace
name: staff
description: Alam El Marateb Staff app.
publish_to: none
environment:
  sdk: ^3.13.2
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
